DROP TABLE IF EXISTS district_records;
CREATE TABLE IF NOT EXISTS district_records(
  id INTEGER(11) NOT NULL PRIMARY KEY 
, district_name VARCHAR(255)
, total_houses INTEGER(11)
, total_population INTEGER(11)
, death INTEGER(11)
, injured INTEGER(1)
, govt_houses_full_destroyed INTEGER(11)
, govt_houses_partial_destroyed INTEGER(11)
, public_house_full_destroyed INTEGER(11)
, public_house_partial_destroyed INTEGER(11)
, displaced_male INTEGER(11) 
, displaced_female INTEGER(11) 
, property_loss VARCHAR(255)
, Incident_Place VARCHAR(255)
, no_of_displaced_family INTEGER(11) 
, cattles_loss INTEGER(11) 
, office VARCHAR(255)
, remarks VARCHAR(255)
);
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (1,'Sindhupalchok',66688,287798,3035,852,0,0,44310,18991,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (2,'Kathmandu',436344,1744240,1210,4634,9990,12915,27640,33215,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (3,'Nuwakot',59215,277471,950,1312,16,0,30000,15000,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (4,'Dhading',73851,336067,702,698,200,28,20000,15000,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (5,'RASUWA',9778,43300,459,748,0,0,8000,1000,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (6,'Gorkha',66506,271061,412,1034,40,14,44607,13236,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (7,'Kavrepalanchok',80720,381937,317,2780,2,93,30000,18545,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (8,'Bhaktapur',68636,304651,314,1887,0,0,7000,2000,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (9,'Lalitpur',109797,468132,174,1224,252,259,16344,5851,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (10,'Dolakha',45688,186557,75,272,6,0,5000,35000,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (11,'Makawanpur',86127,420477,33,127,0,0,363,497,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (12,'Ramechhap',43910,202646,27,27,0,0,17072,23149,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (13,'Solukhumbu',23785,105886,22,80,21,13,2483,6176,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (14,'Okhaldhunga',32502,147984,19,53,11,12,8000,10000,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (15,'Sindhuli',57581,296192,10,63,18,166,4159,8545,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (16,'Sunsari',162407,763487,7,25,1,50,2,21,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (17,'Chitawan',132462,579984,7,95,5,6,2046,3217,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (18,'Bara',108635,687708,5,29,5,2,7,49,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (19,'Parsa',95536,601017,5,23,0,14,16,20,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (20,'Lamjung',42079,167724,5,31,32,95,7430,0,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (21,'Morang',213997,965370,2,45,0,23,2,40,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (22,'Bhojpur',39419,182459,2,8,13,25,1309,2195,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (23,'Kaski',125673,492098,2,30,0,55,174,700,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (24,'Taplejung',26509,127461,1,3,0,53,3,338,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (25,'Dhanusha',138249,754777,1,19,0,0,1,0,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (26,'Sarlahi',132844,769729,1,50,0,0,56,313,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (27,'Rautahat',106668,686722,1,24,0,32,24,170,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (28,'Nawalparasi',128793,643508,1,13,0,0,17,68,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (29,'Tanahu',78309,323288,1,18,0,21,3377,12927,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (30,'Rolpa',23013,136948,1,5,1,15,42,80,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (31,'Rukum',19303,108921,1,1,10,16,61,120,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (32,'Panchthar',41196,191817,0,5,9,56,41,481,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (33,'Ilaam',64502,290254,0,5,5,28,93,393,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (34,'Jhapa',184552,812650,0,19,1,35,1,29,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (35,'Dhankuta',37637,163412,0,2,0,36,15,85,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (36,'Terhathum',22094,101577,0,1,1,11,162,507,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (37,'Shankhuwasabha',34624,158742,0,5,67,79,326,766,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (38,'Khotang',42664,206312,0,3,19,52,1983,4764,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (39,'Udayapur',66557,317532,0,28,3,228,95,205,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (40,'Siraha',177962,637328,0,24,0,1,0,57,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (41,'Saptari',121098,639284,0,16,1,14,0,47,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (42,'Mahottari',111316,627580,0,9,0,13,43,38,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (43,'Rupandehi',163916,880696,0,30,0,0,10,1043,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (44,'Kapilbastu',91321,571936,0,3,0,1,0,24,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (45,'Palpa',59291,261180,0,15,0,120,1060,1510,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (46,'Arghakhanchi',46835,197632,0,2,2,29,140,485,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (47,'Gulmi',64921,280160,0,6,0,100,770,2629,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (48,'Shyanja',68881,289148,0,6,12,91,3119,9695,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (49,'Manang',1400,6538,0,1,2,48,5,68,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (50,'Mustang',3354,13452,0,1,2,19,56,617,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (51,'Myagdi',27762,113641,0,4,0,0,97,490,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (52,'Baglung',61522,268613,0,6,30,36,428,1176,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (53,'Parbat',35719,146590,0,11,9,39,777,1617,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (54,'Dang',9619,55286,0,3,1,19,7,508,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (55,'Pyuthan',7488,36700,0,7,0,0,3,66,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (56,'Salyan',47730,228102,0,2,3,16,18,147,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (57,'Dolpa',41856,208567,0,0,0,0,1,5,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (58,'Mugu',43757,224506,0,0,0,0,0,0,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (59,'Humla',46558,242444,0,0,0,0,0,0,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (60,'Jumla',9479,50858,0,2,0,0,0,2,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (61,'Kalikot',116415,552583,0,0,0,1,2,0,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (62,'Jajarkot',30472,171304,0,1,0,0,0,28,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (63,'Dailekh',48919,261770,0,0,0,0,0,9,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (64,'Surkhet',72863,350804,0,3,0,11,1,31,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (65,'Bardiya',73176,426576,0,2,0,0,0,40,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (66,'Banke',94773,491313,0,0,0,0,0,81,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (67,'Kailali',142480,775709,0,1,0,5,0,4,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (68,'Doti',41440,211746,0,0,0,1,0,0,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (69,'Achhaam',48351,257477,0,0,0,0,0,0,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (70,'Bajura',24908,134912,0,0,0,0,0,1,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (71,'Bajhang',33786,195159,0,0,0,0,0,0,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (72,'Darchula',24618,133274,0,0,0,0,0,0,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (73,'Baitadi',45191,250898,0,0,0,0,0,0,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (74,'Dadeldhura',27045,142094,0,0,0,0,0,1,0,0,'','',0,0,'','');
INSERT INTO district_records(id,district_name,total_houses,total_population,death,injured,govt_houses_full_destroyed,govt_houses_partial_destroyed,public_house_full_destroyed,public_house_partial_destroyed,displaced_male,displaced_female,property_loss,Incident_Place,no_of_displaced_family,cattles_loss,office,remarks) VALUES (75,'Kanchanpur',82152,451248,0,1,0,1,0,0,0,NULL,'','',NULL,NULL,'','');
